// Variant attribute lookup data - loaded from variant JSON files
// This data is used to build payloads when adding new variants

const VARIANT_ATTRIBUTES = {
    // Màu (AttributeId: 3)
    colors: {
        "Cà Phê": { "Id": 77, "AttributeId": 3, "Code": "caphe" },
        "Hồng Đào": { "Id": 100, "AttributeId": 3, "Code": "hongdao" },
        "Hồng Đất": { "Id": 101, "AttributeId": 3, "Code": "hongdat" },
        "Tím Đậm": { "Id": 102, "AttributeId": 3, "Code": "timdam" },
        "Sọc Trắng To": { "Id": 105, "AttributeId": 3, "Code": "soctrangto" },
        "Beo": { "Id": 106, "AttributeId": 3, "Code": "beo" },
        "SỌC NÂU": { "Id": 104, "AttributeId": 3, "Code": "socnau" },
        "SỌC ĐỎ": { "Id": 103, "AttributeId": 3, "Code": "socdo" },
        "Trắng": { "Id": 6, "AttributeId": 3, "Code": "trang" },
        "Đen": { "Id": 7, "AttributeId": 3, "Code": "den" },
        "Đỏ": { "Id": 8, "AttributeId": 3, "Code": "do" },
        "Vàng": { "Id": 9, "AttributeId": 3, "Code": "vang" },
        "Xám": { "Id": 11, "AttributeId": 3, "Code": "xam" },
        "Xanh Lá": { "Id": 29, "AttributeId": 3, "Code": "xanhla" }
    },
    
    // Size Số (AttributeId: 4)
    sizeNumbers: {
        "29": { "Id": 18, "AttributeId": 4, "Code": "29" },
        "30": { "Id": 19, "AttributeId": 4, "Code": "30" },
        "31": { "Id": 20, "AttributeId": 4, "Code": "31" },
        "32": { "Id": 21, "AttributeId": 4, "Code": "32" },
        "1": { "Id": 22, "AttributeId": 4, "Code": "1" },
        "2": { "Id": 23, "AttributeId": 4, "Code": "2" },
        "3": { "Id": 24, "AttributeId": 4, "Code": "3" },
        "35": { "Id": 33, "AttributeId": 4, "Code": "35" },
        "36": { "Id": 34, "AttributeId": 4, "Code": "36" },
        "37": { "Id": 35, "AttributeId": 4, "Code": "37" },
        "38": { "Id": 36, "AttributeId": 4, "Code": "38" }
    },
    
    // Size Chữ (AttributeId: 1)
    sizeText: {
        "XXXL": { "Id": 32, "AttributeId": 1, "Code": "xxxl" },
        "XXL": { "Id": 31, "AttributeId": 1, "Code": "xxl" },
        "S": { "Id": 1, "AttributeId": 1, "Code": "S" },
        "M": { "Id": 2, "AttributeId": 1, "Code": "M" },
        "L": { "Id": 3, "AttributeId": 1, "Code": "L" },
        "XL": { "Id": 4, "AttributeId": 1, "Code": "XL" }
    }
};

// Payload template for AddVariant
const ADD_VARIANT_PAYLOAD_TEMPLATE = {
    "Id": 0,
    "EAN13": null,
    "DefaultCode": null,
    "NameTemplate": null,
    "NameNoSign": null,
    "ProductTmplId": 0,
    "UOMId": 0,
    "UOMName": null,
    "UOMPOId": 0,
    "QtyAvailable": 0,
    "VirtualAvailable": 0,
    "OutgoingQty": null,
    "IncomingQty": null,
    "NameGet": null,
    "POSCategId": null,
    "Price": null,
    "Barcode": null,
    "Image": null,
    "ImageUrl": null,
    "Thumbnails": [],
    "PriceVariant": 0,
    "SaleOK": true,
    "PurchaseOK": true,
    "DisplayAttributeValues": null,
    "LstPrice": 0,
    "Active": true,
    "ListPrice": 0,
    "PurchasePrice": null,
    "DiscountSale": null,
    "DiscountPurchase": null,
    "StandardPrice": 0,
    "Weight": null,
    "Volume": null,
    "OldPrice": null,
    "IsDiscount": false,
    "ProductTmplEnableAll": false,
    "Version": 0,
    "Description": null,
    "LastUpdated": null,
    "Type": "product",
    "CategId": 0,
    "CostMethod": null,
    "InvoicePolicy": "order",
    "Variant_TeamId": 0,
    "Name": "",
    "PropertyCostMethod": null,
    "PropertyValuation": null,
    "PurchaseMethod": "receive",
    "SaleDelay": 0,
    "Tracking": null,
    "Valuation": null,
    "AvailableInPOS": true,
    "CompanyId": null,
    "IsCombo": null,
    "NameTemplateNoSign": null,
    "TaxesIds": [],
    "StockValue": null,
    "SaleValue": null,
    "PosSalesCount": null,
    "Factor": null,
    "CategName": null,
    "AmountTotal": null,
    "NameCombos": [],
    "RewardName": null,
    "Product_UOMId": null,
    "Tags": null,
    "DateCreated": null,
    "InitInventory": null,
    "OrderTag": null,
    "StringExtraProperties": null,
    "CreatedById": null,
    "TaxAmount": null,
    "Error": null,
    "AttributeValues": []
};
